-- MySQL Script generated by MySQL Workbench
-- Wed Jun  7 12:04:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema syspotec_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema syspotec_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `syspotec_test` DEFAULT CHARACTER SET utf8 ;
USE `syspotec_test` ;

-- -----------------------------------------------------
-- Table `syspotec_test`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `syspotec_test`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `cedula` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `syspotec_test`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `syspotec_test`.`Tickets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(200) NULL,
  `numero` INT NOT NULL,
  `prioridad` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `syspotec_test`.`EstadoTickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `syspotec_test`.`EstadoTickets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `syspotec_test`.`AsignadosUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `syspotec_test`.`AsignadosUsuarios` (
  `idUsuario` INT NOT NULL,
  `idTicket` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `idEstado` INT NULL,
  PRIMARY KEY (`idUsuario`, `idTicket`),
  INDEX `Fk_AsignadosUsuarios_Ticket_Id_idx` (`idTicket` ASC) VISIBLE,
  INDEX `Fk_AsignadosUsuarios_Estado_Id_idx` (`idEstado` ASC) VISIBLE,
  CONSTRAINT `Fk_AsignadosUsuarios_Usuario_Id`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `syspotec_test`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_AsignadosUsuarios_Ticket_Id`
    FOREIGN KEY (`idTicket`)
    REFERENCES `syspotec_test`.`Tickets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_AsignadosUsuarios_Estado_Id`
    FOREIGN KEY (`idEstado`)
    REFERENCES `syspotec_test`.`EstadoTickets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
